Repository CfM47/TechnicalDowntimeManager-FE, pull requests merged in 2025-02, with the labels that each got.

#138 fixed Pagination bug
  src/components/containers/pagination-container/index.tsx
Labels: bug

#139 feat/technicians-performance
  src/app/reports/techniciansPerformance/page.tsx
  src/components/pages/techniciansPerformance/components/Body.tsx
  src/components/pages/techniciansPerformance/index.tsx
  src/lib/reports.ts
  src/services/features/technician.ts
  src/services/routes/routes.ts
  src/types/technician.ts
Labels: enhancement

#141 refactor unnecesary code
  src/components/pages/lastYearDowntimes/components/Filters.tsx
Labels: refactor

#140 4th report
  src/app/reports/technicianInterventions/page.tsx
  src/components/pages/deptTransferHistory/index.tsx
  src/components/pages/maintenanceHistory/index.tsx
  src/components/pages/technicianInterventions/components/Body.tsx
  src/components/pages/technicianInterventions/components/Filters.tsx
  src/components/pages/technicianInterventions/index.tsx
  src/components/pages/transferHistory/index.tsx
  src/lib/reports.ts
  src/services/features/technician.ts
  src/services/routes/routes.ts
  src/types/technician.ts
Labels: enhancement

#143 Feat/export-button
  src/components/common/export-button/index.tsx
  src/components/pages/defectiveEquipments/index.tsx
  src/components/pages/deptTransferHistory/index.tsx
  src/components/pages/lastYearDowntimes/index.tsx
  src/components/pages/maintenanceHistory/index.tsx
  src/components/pages/technicianInterventions/index.tsx
  src/components/pages/techniciansPerformance/index.tsx
  src/components/pages/transferHistory/index.tsx
  src/hooks/useFetchOptions.tsx
  src/services/features/downtime.ts
  src/services/features/equipment.ts
  src/services/features/maintenance.ts
  src/services/features/technician.ts
  src/services/features/transfer.ts
  src/services/routes/routes.ts
  src/types/utils.ts
Labels: enhancement
