Repository CfM47/TechnicalDowntimeManager-FE, pull requests merged in 2025-01, with the labels that each got.

#76 delete sign up option
  src/components/forms/sign-up/index.tsx
  src/components/modals/auth-modal/components/BodyContent.tsx
Labels: enhancement

#79 Signin-refactorized
  src/components/common/side-menu/index.tsx
  src/components/forms/sign-in/index.tsx
  src/components/forms/sign-in/schema.ts
  src/components/layouts/home/components/Navbar.tsx
  src/components/modals/auth-modal/components/BodyContent.tsx
  src/components/modals/auth-modal/components/FooterContent.tsx
  src/components/modals/auth-modal/index.tsx
  src/components/modals/sign-in-modal/index.tsx
Labels: refactor

#80 styled hero
  package.json
  pnpm-lock.yaml
  src/components/pages/home/components/Hero.tsx
Labels: style

#82 refactor: rename transfer form fields for clarity
  src/components/forms/create-transfer/index.tsx
  src/components/forms/create-transfer/schema.ts
  src/components/forms/edit-transfer/index.tsx
  src/components/forms/edit-transfer/schema.ts
Labels: bug

#83 add delete modal component and update modal button styles
  src/components/common/modal/index.tsx
  src/components/modals/delete-modal/index.tsx
Labels: enhancement

#84 edit modals connected to database
  src/components/forms/edit-downtime/index.tsx
  src/components/forms/edit-equipment/index.tsx
  src/components/forms/edit-maintenance/index.tsx
  src/components/forms/edit-rate/index.tsx
  src/components/forms/edit-transfer/index.tsx
  src/components/forms/edit-user/index.tsx
  src/components/modals/edit-downtime-modal/index.tsx
  src/components/modals/edit-equipment-modal/index.tsx
  src/components/modals/edit-maintenance-modal/index.tsx
  src/components/modals/edit-rate-modal/index.tsx
  src/components/modals/edit-transfer-modal/index.tsx
  src/components/modals/edit-user-modal/index.tsx
  src/components/pages/downtimes/components/RowActions.tsx
  src/components/pages/equipment/components/RowActions.tsx
  src/components/pages/maintenances/components/RowActions.tsx
  src/components/pages/rate/components/RowActions.tsx
  src/components/pages/transfers/components/RowActions.tsx
  src/components/pages/user/components/RowActions.tsx
Labels: enhancement

#85 fix route of role
  src/services/routes/routes.ts
Labels: bug

#87 feat: add delete functionality to various row actions components
  src/components/pages/downtimes/components/RowActions.tsx
  src/components/pages/equipment/components/RowActions.tsx
  src/components/pages/maintenances/components/RowActions.tsx
  src/components/pages/rate/components/RowActions.tsx
  src/components/pages/transfers/components/RowActions.tsx
  src/components/pages/user/components/RowActions.tsx
Labels: enhancement

#88 Fix form bugs
  src/components/forms/create-maintenance/index.tsx
  src/components/forms/create-rate/index.tsx
  src/components/forms/edit-maintenance/index.tsx
  src/components/forms/edit-rate/index.tsx
  src/components/forms/edit-user/index.tsx
  src/components/rhf/rhf-numeric-input/index.tsx
Labels: enhancement

#89 Implement Authentication services
  src/components/common/initials-avatar/index.tsx
  src/components/forms/sign-in/index.tsx
  src/components/layouts/home/components/Navbar.tsx
  src/lib/utils.ts
  src/services/features/auth.ts
  src/services/routes/routes.ts
  src/stores/sesionStore.tsx
  src/types/auth.ts
Labels: enhancement

#90 Update session store
  src/stores/sesionStore.tsx
Labels: enhancement

#91 added logout function
  src/components/layouts/home/components/Navbar.tsx
Labels: enhancement

#92 added style to logout buttom
  src/components/layouts/home/components/Navbar.tsx
Labels: style

#93 Render pages conditionally
  src/components/containers/private-route-container/index.tsx
  src/components/forms/sign-in/index.tsx
  src/components/layouts/home/components/Navbar.tsx
  src/components/pages/downtimes/index.tsx
  src/stores/sesionStore.tsx
  src/types/auth.ts
Labels: enhancement

#97 added the same autentication logic to the responsive side menu
  src/components/common/side-menu/index.tsx
Labels: bug

#98 fix bug with the security of the endpoints
  src/components/containers/private-route-container/index.tsx
  src/components/pages/equipment/index.tsx
  src/components/pages/maintenances/index.tsx
  src/components/pages/rate/index.tsx
  src/components/pages/transfers/index.tsx
  src/components/pages/user/index.tsx
Labels: bug

#108 Refactor: Log out button
  src/components/common/logout-button/index.tsx
  src/components/common/side-menu/index.tsx
  src/components/layouts/home/components/Navbar.tsx
Labels: refactor

#109 Feat/toast errors
  package.json
  pnpm-lock.yaml
  src/components/common/toast-message/index.tsx
  src/components/containers/toast-provider/index.tsx
  src/components/forms/create-downtime/index.tsx
  src/components/forms/create-equipment/index.tsx
  src/components/forms/create-maintenance/index.tsx
  src/components/forms/create-rate/index.tsx
  src/components/forms/create-transfer/index.tsx
  src/components/forms/create-user/index.tsx
  src/components/forms/edit-downtime/index.tsx
  src/components/forms/edit-equipment/index.tsx
  src/components/forms/edit-maintenance/index.tsx
  src/components/forms/edit-rate/index.tsx
  src/components/forms/edit-transfer/index.tsx
  src/components/forms/edit-user/index.tsx
  src/components/forms/sign-in/index.tsx
  src/components/layouts/home/index.tsx
  src/components/modals/delete-modal/index.tsx
  src/lib/utils.ts
Labels: enhancement

#110 added useRefreshPage hook
  src/components/forms/create-downtime/index.tsx
  src/components/forms/create-equipment/index.tsx
  src/components/forms/create-maintenance/index.tsx
  src/components/forms/create-rate/index.tsx
  src/components/forms/create-transfer/index.tsx
  src/components/forms/create-user/index.tsx
  src/components/forms/edit-downtime/index.tsx
  src/components/forms/edit-equipment/index.tsx
  src/components/forms/edit-maintenance/index.tsx
  src/components/forms/edit-rate/index.tsx
  src/components/forms/edit-transfer/index.tsx
  src/components/forms/edit-user/index.tsx
  src/components/forms/sign-in/index.tsx
  src/components/modals/delete-modal/index.tsx
  src/hooks/useRefreshPage.tsx
  src/lib/utils.ts
Labels: enhancement

#111 update schema and status and type options of some entities
  src/components/forms/create-equipment/index.tsx
  src/components/forms/create-equipment/schema.ts
  src/components/forms/create-maintenance/index.tsx
  src/components/forms/create-maintenance/schema.ts
  src/components/forms/create-transfer/index.tsx
  src/components/forms/create-transfer/schema.ts
  src/components/forms/edit-equipment/index.tsx
  src/components/forms/edit-equipment/schema.ts
  src/components/forms/edit-maintenance/index.tsx
  src/components/forms/edit-maintenance/schema.ts
  src/components/forms/edit-transfer/index.tsx
  src/components/forms/edit-transfer/schema.ts
Labels: enhancement

#114 added format to dates using daysjs
  package.json
  pnpm-lock.yaml
  src/components/pages/downtimes/components/Body.tsx
  src/components/pages/equipment/components/Body.tsx
  src/components/pages/maintenances/components/Body.tsx
  src/components/pages/rate/components/Body.tsx
  src/components/pages/transfers/components/Body.tsx
  src/lib/utils.ts
Labels: enhancement

#115 feat/downtime-status-limit
  src/components/forms/create-downtime/index.tsx
  src/components/forms/create-downtime/schema.ts
  src/components/forms/edit-downtime/index.tsx
  src/components/forms/edit-downtime/schema.ts
Labels: enhancement

#116 create reports page
  src/app/reports/page.tsx
  src/components/common/report-card/index.tsx
  src/components/layouts/home/components/Navbar.tsx
  src/components/pages/reports/index.tsx
  src/lib/reports.ts
Labels: enhancement

#118 Fix/enums
  src/components/forms/create-downtime/index.tsx
  src/components/forms/create-downtime/schema.ts
  src/components/forms/create-equipment/index.tsx
  src/components/forms/create-equipment/schema.ts
  src/components/forms/create-maintenance/index.tsx
  src/components/forms/create-maintenance/schema.ts
  src/components/forms/create-transfer/index.tsx
  src/components/forms/create-transfer/schema.ts
  src/components/forms/edit-downtime/index.tsx
  src/components/forms/edit-downtime/schema.ts
  src/components/forms/edit-equipment/index.tsx
  src/components/forms/edit-equipment/schema.ts
  src/components/forms/edit-maintenance/index.tsx
  src/components/forms/edit-maintenance/schema.ts
  src/components/forms/edit-transfer/index.tsx
  src/components/forms/edit-transfer/schema.ts
  src/components/pages/equipment/components/Body.tsx
  src/lib/enums.ts
  src/lib/utils.ts
  src/types/equipment.ts
Labels: enhancement

#120 Make Role an enum
  src/components/common/side-menu/index.tsx
  src/components/containers/private-route-container/index.tsx
  src/components/forms/create-user/index.tsx
  src/components/forms/create-user/schema.ts
  src/components/forms/edit-user/index.tsx
  src/components/forms/edit-user/schema.ts
  src/components/forms/sign-in/index.tsx
  src/components/layouts/home/components/Navbar.tsx
  src/components/pages/downtimes/index.tsx
  src/components/pages/equipment/index.tsx
  src/components/pages/maintenances/index.tsx
  src/components/pages/rate/index.tsx
  src/components/pages/reports/index.tsx
  src/components/pages/transfers/index.tsx
  src/components/pages/user/components/Body.tsx
  src/components/pages/user/index.tsx
  src/hooks/useFetchOptions.tsx
  src/lib/constants.ts
  src/lib/enums.ts
  src/services/features/role.ts
  src/services/routes/routes.ts
  src/types/auth.ts
  src/types/role.ts
  src/types/user.ts
  src/types/utils.ts
Labels: enhancement

#121 logic added
  src/components/forms/create-rate/index.tsx
  src/components/forms/edit-rate/index.tsx
Labels: enhancement

#122 now the user cannot change the origin department of an equipment
  src/components/forms/create-transfer/index.tsx
  src/components/forms/create-transfer/schema.ts
  src/components/forms/edit-transfer/index.tsx
  src/components/forms/edit-transfer/schema.ts
  src/components/rhf/rhf-submit-button/index.tsx
Labels: refactor

#124 Feat/integrate-pagination
  src/app/downtimes/page.tsx
  src/app/equipment/page.tsx
  src/app/maintenances/page.tsx
  src/app/rate/page.tsx
  src/app/transfers/page.tsx
  src/app/user/page.tsx
  src/components/common/entity-page/index.tsx
  src/components/containers/pagination-container/index.tsx
  src/components/pages/downtimes/index.tsx
  src/components/pages/equipment/index.tsx
  src/components/pages/maintenances/index.tsx
  src/components/pages/rate/index.tsx
  src/components/pages/transfers/index.tsx
  src/components/pages/user/index.tsx
  src/components/ui/pagination.tsx
  src/hooks/useFilters.tsx
  src/services/features/department.ts
  src/services/features/downtime.ts
  src/services/features/equipment.ts
  src/services/features/maintenance.ts
  src/services/features/rate.ts
  src/services/features/technician.ts
  src/services/features/transfer.ts
  src/services/features/user.ts
  src/services/routes/types.ts
  src/services/routes/utils.ts
  src/types/downtime.ts
  src/types/equipment.ts
  src/types/maitenance.ts
  src/types/rate.ts
  src/types/technician.ts
  src/types/transfer.ts
  src/types/user.ts
Labels: enhancement

#125 translate to english
  src/components/forms/create-downtime/index.tsx
  src/components/forms/create-equipment/index.tsx
  src/components/forms/create-maintenance/index.tsx
  src/components/forms/create-rate/index.tsx
  src/components/forms/create-transfer/index.tsx
  src/components/forms/create-user/index.tsx
  src/components/forms/edit-downtime/index.tsx
  src/components/forms/edit-equipment/index.tsx
  src/components/forms/edit-maintenance/index.tsx
  src/components/forms/edit-rate/index.tsx
  src/components/forms/edit-transfer/index.tsx
  src/components/forms/edit-user/index.tsx
  src/components/forms/sign-in/index.tsx
  src/components/layouts/home/components/Navbar.tsx
  src/components/modals/create-downtime-modal/index.tsx
  src/components/modals/create-equipment-modal/index.tsx
  src/components/modals/create-maintenance-modal/index.tsx
  src/components/modals/create-rate-modal/index.tsx
  src/components/modals/create-transfer-modal/index.tsx
  src/components/modals/create-user-modal/index.tsx
  src/components/modals/delete-modal/index.tsx
  src/components/modals/edit-downtime-modal/index.tsx
  src/components/modals/edit-equipment-modal/index.tsx
  src/components/modals/edit-maintenance-modal/index.tsx
  src/components/modals/edit-rate-modal/index.tsx
  src/components/modals/edit-transfer-modal/index.tsx
  src/components/modals/edit-user-modal/index.tsx
  src/components/modals/sign-in-modal/index.tsx
  src/components/pages/downtimes/index.tsx
  src/components/pages/equipment/index.tsx
  src/components/pages/home/components/Hero.tsx
  src/components/pages/maintenances/index.tsx
  src/components/pages/rate/index.tsx
  src/components/pages/reports/index.tsx
  src/components/pages/transfers/index.tsx
  src/components/pages/user/index.tsx
  src/lib/reports.ts
Labels: enhancement

#128 Fix user forms bussines logic
  src/components/containers/pagination-container/index.tsx
  src/components/forms/create-user/index.tsx
  src/components/forms/create-user/schema.ts
  src/components/forms/edit-user/index.tsx
Labels: enhancement

#127 Feat/add filters
  src/components/common/entity-page/index.tsx
  src/components/common/option-select/index.tsx
  src/components/pages/downtimes/components/Filters.tsx
  src/components/pages/downtimes/index.tsx
  src/components/pages/equipment/components/Filters.tsx
  src/components/pages/equipment/index.tsx
  src/components/pages/maintenances/components/Filters.tsx
  src/components/pages/maintenances/index.tsx
  src/components/pages/rate/components/Body.tsx
  src/components/pages/rate/components/Filters.tsx
  src/components/pages/rate/index.tsx
  src/components/pages/transfers/components/Filters.tsx
  src/components/pages/transfers/index.tsx
  src/components/pages/user/components/Filters.tsx
  src/components/pages/user/index.tsx
  src/types/equipment.ts
Labels: enhancement

#130 feat: add debounce functionality to useFilters hook for improved perf…
  package.json
  pnpm-lock.yaml
  src/hooks/useFilters.tsx
Labels: enhancement

#129 Fixed size in options fetching
  src/hooks/useFetchOptions.tsx
  src/services/features/department.ts
  src/types/department.ts
  src/types/equipment.ts
  src/types/technician.ts
Labels: bug

#131 convert to english other phrases
  src/components/common/report-card/index.tsx
  src/components/forms/create-downtime/schema.ts
  src/components/forms/create-equipment/schema.ts
  src/components/forms/create-maintenance/schema.ts
  src/components/forms/create-rate/schema.ts
  src/components/forms/create-transfer/schema.ts
  src/components/forms/create-user/schema.ts
  src/components/forms/edit-downtime/schema.ts
  src/components/forms/edit-equipment/schema.ts
  src/components/forms/edit-maintenance/schema.ts
  src/components/forms/edit-rate/schema.tsx
  src/components/forms/edit-transfer/schema.ts
  src/components/forms/edit-user/schema.ts
  src/components/forms/sign-in/schema.ts
Labels: enhancement

#132 feat: implement maintenance history page with pagination and actions
  src/app/reports/maintenanceHistory/page.tsx
  src/components/common/entity-page/index.tsx
  src/components/common/option-select/index.tsx
  src/components/common/report-card/index.tsx
  src/components/pages/maintenanceHistory/components/Body.tsx
  src/components/pages/maintenanceHistory/components/Filters.tsx
  src/components/pages/maintenanceHistory/index.tsx
  src/components/pages/reports/index.tsx
  src/lib/reports.ts
  src/types/maitenance.ts
Labels: enhancement

#133 Feat/reports-downtimes-maintenances
  src/app/reports/defectiveEquipments/page.tsx
  src/app/reports/lastYearDowntimes/page.tsx
  src/components/pages/defectiveEquipments/components/Body.tsx
  src/components/pages/defectiveEquipments/index.tsx
  src/components/pages/lastYearDowntimes/components/Body.tsx
  src/components/pages/lastYearDowntimes/components/Filters.tsx
  src/components/pages/lastYearDowntimes/index.tsx
  src/components/pages/maintenanceHistory/index.tsx
  src/lib/reports.ts
  src/services/features/downtime.ts
  src/services/features/equipment.ts
  src/services/routes/routes.ts
  src/types/equipment.ts
Labels: enhancement

#134 feat/3rd-7th-reports
  src/app/reports/deptTransferHistory/page.tsx
  src/app/reports/transferHistory/page.tsx
  src/components/common/report-card/index.tsx
  src/components/pages/deptTransferHistory/components/Body.tsx
  src/components/pages/deptTransferHistory/components/Filters.tsx
  src/components/pages/deptTransferHistory/index.tsx
  src/components/pages/transferHistory/components/Body.tsx
  src/components/pages/transferHistory/components/Filters.tsx
  src/components/pages/transferHistory/index.tsx
  src/lib/reports.ts
  src/types/transfer.ts
Labels: enhancement
